name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install pip deps
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2

      - run: echo "python-greetings repozitorija klonesana"

      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: 4e911440a9886c7c26ccbb4eb55f0bc2a5067b51
          fetch-depth: 0

      - run: echo "Requirments instalesana..."

      - run: cd python-greetings; pip3.9 install -r requirements.txt

  deploy-to-dev:
    name: Deploy to dev
    runs-on: self-hosted
    needs: install-pip-deps
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'

  tests-on-dev:
    name: Tests on dev
    runs-on: self-hosted
    needs: deploy-to-dev
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          enviroment: 'dev'

  deploy-to-staging:
    name: Deploy to staging
    runs-on: self-hosted
    needs: tests-on-dev
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          enviroment: 'staging'

  tests-on-staging:
    name: Tests on staging
    runs-on: self-hosted
    needs: deploy-to-staging
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          enviroment: 'dev'

  deploy-to-preprod:
    name: Deploy to preprod
    runs-on: self-hosted
    needs: tests-on-staging
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          enviroment: 'preprod'

  tests-on-preprod:
    name: Tests on preprod
    runs-on: self-hosted
    needs: deploy-to-preprod
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          enviroment: 'dev'

  deploy-to-prod:
    name: Deploy to prod
    runs-on: self-hosted
    needs: tests-on-preprod
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          enviroment: 'prod'

  tests-on-prod:
    name: Tests on prod
    runs-on: self-hosted
    needs: deploy-to-prod
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          enviroment: 'dev'